
worker_processes  1;
error_log logs/error.log debug;
env SSLKEYLOGFILE;

events {
    worker_connections  1024;
}
http {
    server {
        listen       8445 ssl;
        server_name  localhost;

        ssl_certificate      server.crt;
        ssl_certificate_key  server.key;

        location / {
            return 200 "Hello World\n";
        }
        
        location /env {
            content_by_lua_block {
                ngx.say("SSLKEYLOGFILE: ", os.getenv("SSLKEYLOGFILE") or "nil")
            }
        }
    }
}
